// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlAc963fP-wGsXq3CmpLjeretHLrPoUmw',
    appId: '1:404230939836:web:24447d50c9677b9dc95cb9',
    messagingSenderId: '404230939836',
    projectId: 'movereminder-8d319',
    authDomain: 'movereminder-8d319.firebaseapp.com',
    storageBucket: 'movereminder-8d319.firebasestorage.app',
    measurementId: 'G-9RH5LKJSG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP0tAQRrkby31yeA0CWqSqK7TBEQHNtnQ',
    appId: '1:404230939836:android:ee8a561853d6d0b9c95cb9',
    messagingSenderId: '404230939836',
    projectId: 'movereminder-8d319',
    storageBucket: 'movereminder-8d319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBRIFcUSXInoz6YQvkeb-AAN9kN4lSkj4',
    appId: '1:404230939836:ios:46cefe23a3d4a499c95cb9',
    messagingSenderId: '404230939836',
    projectId: 'movereminder-8d319',
    storageBucket: 'movereminder-8d319.firebasestorage.app',
    iosBundleId: 'com.example.projektPierwszaWersja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBRIFcUSXInoz6YQvkeb-AAN9kN4lSkj4',
    appId: '1:404230939836:ios:46cefe23a3d4a499c95cb9',
    messagingSenderId: '404230939836',
    projectId: 'movereminder-8d319',
    storageBucket: 'movereminder-8d319.firebasestorage.app',
    iosBundleId: 'com.example.projektPierwszaWersja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlAc963fP-wGsXq3CmpLjeretHLrPoUmw',
    appId: '1:404230939836:web:3cc993850ea27ad2c95cb9',
    messagingSenderId: '404230939836',
    projectId: 'movereminder-8d319',
    authDomain: 'movereminder-8d319.firebaseapp.com',
    storageBucket: 'movereminder-8d319.firebasestorage.app',
    measurementId: 'G-LPDFJDC1Z9',
  );
}
